In [109]:
import json
import requests
from pandas.io.json import json_normalize
import pandas as pd

In [110]:
l = []
for i in range(22):    
    url= f'https://searchapi.wyscout.com/api/v1/search/results.json?search%5Btime_frame%5D=default&search%5Bcompetition%5D=155&search%5Byouth_stats%5D=false&count=30&page={i}&sort=market_value+desc&language=es&columns=name%2Cid%2Cimage%2Ccurrent_team_logo%2Ccurrent_team_color%2Cbirth_country_name%2Cpassport_country_names%2Ccurrent_team_name%2Cmarket_value%2Ctotal_matches%2Cminutes_on_field%2Cpositions%2Cage%2Ccontract_expires%2Cgoals%2Cgoals_tagged%2Cxg_shot%2Cfoot%2Cheight%2Cweight%2Con_loan&token=98de50b5ada2adab5da2b5796031f14751c9c6a6&groupId=1110432&subgroupId=163958'
    headers = {"User-Agent":"Mozilla/5.0"}
    response = requests.get(url, headers=headers).json() 
    flattened_data = json_normalize(response['players'])
    l.append(flattened_data)
dataframe = pd.concat(l)
dataframe = dataframe.reset_index()
dataframe.head()

,index,age,birth_country_code,birth_country_name,birth_date,birth_day,contract_expires,current_team_color,current_team_logo,current_team_name,...,positions,primary_position,primary_position_percent,secondary_position,secondary_position_percent,third_position,third_position_percent,total_matches,weight,xg_shot
0,0,19,MEX,Mexico,2000-06-09,2000-06-09,2024-06-30,14ad58,https://cdn5.wyscout.com/photos/team/public/45...,Real Betis,...,"[LW, RW, AMF]",LW,35,RW,31,AMF,16,15,58,1.37
1,1,26,ARG,Argentina,1992-12-15,1992-12-15,2020-06-30,000000,https://cdn5.wyscout.com/photos/team/public/59...,Monterrey,...,"[AMF, RW, LW]",AMF,37,RW,10,LW,10,19,77,1.09
2,2,25,MEX,Mexico,1993-09-29,1993-09-29,2022-06-30,000000,https://cdn5.wyscout.com/photos/team/public/92...,Tigres UANL,...,"[LCB, CB]",LCB,71,CB,14,None,0,15,77,0.49
3,3,25,MEX,Mexico,1994-02-15,1994-02-15,2023-06-30,000000,https://cdn5.wyscout.com/photos/team/public/59...,Monterrey,...,"[AMF, LW]",AMF,52,LW,10,None,0,30,64,5.09
4,4,25,ARG,Argentina,1994-04-12,1994-04-12,None,000000,https://cdn5.wyscout.com/photos/team/public/46...,América,...,"[LCMF, LDMF, DMF]",LCMF,41,LDMF,23,DMF,18,44,80,3.40

In [ ]:
league_id = {'México':'155', 'Venezuela':'163', 'Argentina': '87'}

In [111]:
dataframe.to_excel('wyscout_ligamx.xlsx', index=False)